<?php
/**
 * Plugin Name:       WooCommerce BOM & Stock Manager
 * Plugin URI:        https://github.com/croix/wordpress-bom
 * Description:       Bill-of-materials and component-level stock management for WooCommerce — made-to-order component consumption, manufacture orders, and a full stock ledger.
 * Version:           1.0.1
 * Requires at least: 6.5
 * Requires PHP:      8.1
 * Requires Plugins:  woocommerce
 * WC requires at least: 8.5
 * Author:            Poor Vida
 * Text Domain:       wcbom
 * Domain Path:       /languages
 * Update URI:        https://github.com/croix/wordpress-bom
 *
 * @package WCBOM
 */

defined( 'ABSPATH' ) || exit;

define( 'WCBOM_VERSION', '1.0.1' );
define( 'WCBOM_PLUGIN_FILE', __FILE__ );
define( 'WCBOM_PLUGIN_DIR', __DIR__ );
// Keep in sync with the "WC requires at least" header above.
define( 'WCBOM_MIN_WC_VERSION', '8.5' );

$wcbom_autoload = __DIR__ . '/vendor/autoload.php';
if ( ! file_exists( $wcbom_autoload ) ) {
	// Missing entirely when this was installed from GitHub's "Code" →
	// "Download ZIP" button (or a "Source code (zip)" link) instead of the
	// built release asset — that raw repo checkout never includes
	// vendor/, since it's gitignored and only generated by
	// bin/build-release-zip.sh. Every WCBOM\ class reference below would
	// otherwise fatal with a cryptic "Class not found" the moment
	// anything actually calls one (e.g. the activation hook) — bail out
	// clearly here instead.
	add_action(
		'admin_notices',
		static function () {
			echo '<div class="notice notice-error"><p>' . esc_html__( 'WooCommerce BOM & Stock Manager could not find its own dependencies (vendor/autoload.php is missing) and cannot run. This usually means it was installed from GitHub\'s "Download ZIP" button instead of the built release — download the wc-bom-stock-X.Y.Z.zip file from the Releases page instead.', 'wcbom' ) . '</p></div>';
		}
	);
	return;
}
require_once $wcbom_autoload;
unset( $wcbom_autoload );

register_activation_hook( __FILE__, array( \WCBOM\Install\Schema::class, 'install' ) );

register_deactivation_hook(
	__FILE__,
	static function () {
		$timestamp = wp_next_scheduled( \WCBOM\Reports\LowStockDigest::HOOK );
		if ( false !== $timestamp ) {
			wp_unschedule_event( $timestamp, \WCBOM\Reports\LowStockDigest::HOOK );
		}
	}
);

add_action( 'before_woocommerce_init', array( \WCBOM\Integrations\Hpos::class, 'declare_compatibility' ) );

add_action(
	'plugins_loaded',
	function () {
		if ( ! class_exists( 'WooCommerce' ) ) {
			add_action(
				'admin_notices',
				function () {
					echo '<div class="notice notice-error"><p>' . esc_html__( 'WooCommerce BOM & Stock Manager requires WooCommerce to be installed and active.', 'wcbom' ) . '</p></div>';
				}
			);
			return;
		}

		// An installed-but-too-old WooCommerce could still be "active" (WP
		// core has no built-in "Requires WC at least" enforcement, unlike
		// its own "Requires at least" WP-version header) — deactivate
		// gracefully with a clear notice rather than risk fataling on a
		// missing WC API deeper in Plugin::init(). BUILD_PLAN.md §12.
		if ( version_compare( WC_VERSION, WCBOM_MIN_WC_VERSION, '<' ) ) {
			deactivate_plugins( plugin_basename( WCBOM_PLUGIN_FILE ) );
			add_action(
				'admin_notices',
				function () {
					printf(
						'<div class="notice notice-error"><p>%s</p></div>',
						esc_html(
							sprintf(
								/* translators: 1: minimum required WooCommerce version, 2: installed WooCommerce version */
								__( 'WooCommerce BOM & Stock Manager requires WooCommerce %1$s or newer (found %2$s) and has been deactivated.', 'wcbom' ),
								WCBOM_MIN_WC_VERSION,
								WC_VERSION
							)
						)
					);
				}
			);
			return;
		}

		\WCBOM\Install\Schema::maybe_upgrade();
		\WCBOM\Plugin::instance()->init();
	}
);

if ( defined( 'WP_CLI' ) && WP_CLI ) {
	\WP_CLI::add_command( 'wcbom', \WCBOM\Cli\Commands::class );
}
